services:
  - type: web
    name: smartagro
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        value: https://your-render-app.onrender.com
      - key: DB_CONNECTION
        value: mongodb
      - key: MONGODB_URI
        value: mongodb+srv://<username>:<password>@<cluster>.mongodb.net/?appName=<appName>
      - key: DB_DATABASE
        value: SmartAgro
      - key: SESSION_DRIVER
        value: file
      - key: CACHE_STORE
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: MAIL_MAILER
        value: resend
      - key: MAIL_FROM_ADDRESS
        value: onboarding@resend.dev
      - key: MAIL_FROM_NAME
        value: SmartAgro
      - key: VITE_APP_NAME
        value: SmartAgro
    autoDeploy: true
